import {StyleSheet, Dimensions } from 'react-native'

const styles = StyleSheet.create({
    body: {
        backgroundColor: '#0D2235',     
        width: '100%', 
        height: '100%',  
    },
    imagen: {
        width: '40%', 
        height: '20%',
        resizeMode: 'contain', 
        marginTop: 5,
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    heading1: {
        color: '#d7db6d',
        textAlign: 'center',
        fontWeight: '700', 
        marginBottom: 5,
        fontSize: 20,
            
    },
    heading1B: {
        justifyContent: 'center',
        alignItems: 'center',
        fontStyle: 'italic',
        backgroundColor: '#fff',
        color: '#13130c',
        textAlign: 'center',
        fontWeight: '700', 
        marginBottom: 5,
        fontSize: 20,
        padding: 5,
        marginLeft: Dimensions.get('screen').width * 0.1,
        marginRight: Dimensions.get('screen').width * 0.1, 
        borderRadius: 10,
    },
    heading1C: {
        color: '#00d54e',
        textAlign: 'center',
        fontWeight: '700', 
        fontStyle: 'italic',
        marginBottom: 5,
        fontSize: 20,
        padding: 5,
        marginLeft: Dimensions.get('screen').width * 0.1,
        marginRight: Dimensions.get('screen').width * 0.1, 
        borderRadius: 10,
    },
    heading1Api: {
        color: '#878b88',
        textAlign: 'center',
        fontWeight: '700', 
        fontStyle: 'italic',
        marginBottom: 5,
        fontSize: 20,
        padding: 5,
        marginLeft: Dimensions.get('screen').width * 0.1,
        marginRight: Dimensions.get('screen').width * 0.1, 
        borderRadius: 10,
    },
    pseudoBarra: {
        backgroundColor: '#66A2FE',
        height: 6,
        width: 100,
        marginLeft: 'auto',
        marginTop: 10,
        marginBottom: 10,
        marginRight: 'auto',
    },
    formulario: {
        width: Dimensions.get('screen').width * 0.8,
        marginLeft: 'auto',
        marginTop: 10,
        marginBottom: 10,
        marginRight: 'auto',
    },
    inputSubmit: {
        marginTop: 20,
        backgroundColor: '#9497ff',
        padding: 10,
        borderRadius: 10,
    },
    textSubmit: {
        textAlign: 'center',
        color: '#fff',
        textTransform: 'uppercase',
        fontWeight: '700',
    },
    textLabel: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
        marginBottom: 10,
    },
    select: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
        height: 35,
        fontSize: 24,
        fontWeight: '700',
        marginBottom: 10,
        borderRadius: 10,
        paddingLeft: 5,
        paddingRight: 5,
    },
    imgBtnDropDown: {
        width: 20,
        height: 20,
        
    },
    optionVisibility: {
        backgroundColor: 'white',
        height: 80,
        borderRadius: 10,
        elevation: 5,
        position: 'absolute',
        top: 75,
        width: '100%',
        zIndex: 2,
        paddingLeft: 5,
    },
    errorValidate: {
        backgroundColor: '#ea1313',
        color: '#FFF',
        padding: 8,
        fontSize: 15,
        textTransform: 'uppercase',
        fontWeight: 'bold',
        textAlign: 'center',
        marginLeft: Dimensions.get('screen').width * 0.1,
        marginRight: Dimensions.get('screen').width * 0.1,
        borderRadius: 10,
    },
    contenedorResultado: {
        marginTop: 40,
        backgroundColor: '#bae9eb',
        color: '#FFF',
        padding: 8,
        fontSize: 15,
        textTransform: 'uppercase',
        textAlign: 'center',
        marginLeft: Dimensions.get('screen').width * 0.1,
        marginRight: Dimensions.get('screen').width * 0.1,
        borderRadius: 10,
    },
    contenedorResultadoRow: {
        display: 'flex',
        flexDirection: 'row',   
    },
    textResultadoTitle: {
        fontWeight: 'bold',
    },
});

export default styles;
